name: tarea1-nlp
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy=2.0.0
  - scikit-learn=1.2.2
  - matplotlib
  - seaborn
  - spacy=3.5.3
  - nltk
  - gensim=4.3.1
  - tqdm
  - scipy=1.10.1
  - pip:
      - es-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.5.0/es_core_news_sm-3.5.0-py3-none-any.whl
